//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDashboard.reoSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REOPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels")]
    [System.SerializableAttribute()]
    public partial class REOPropertyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.AccessInfo AccessInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.AdditionalPropertyInfo AddlPropInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.AssetInfo AssetInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.Person AssetMgrInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.Person BrokerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.InitialServices InitialServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.PropertyHistoryItem[] PropertyHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientDashboard.reoSvc.UtilityStatus[] UtilStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.AccessInfo AccessInfo {
            get {
                return this.AccessInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessInfoField, value) != true)) {
                    this.AccessInfoField = value;
                    this.RaisePropertyChanged("AccessInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.AdditionalPropertyInfo AddlPropInfo {
            get {
                return this.AddlPropInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AddlPropInfoField, value) != true)) {
                    this.AddlPropInfoField = value;
                    this.RaisePropertyChanged("AddlPropInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.AssetInfo AssetInfo {
            get {
                return this.AssetInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetInfoField, value) != true)) {
                    this.AssetInfoField = value;
                    this.RaisePropertyChanged("AssetInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.Person AssetMgrInfo {
            get {
                return this.AssetMgrInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetMgrInfoField, value) != true)) {
                    this.AssetMgrInfoField = value;
                    this.RaisePropertyChanged("AssetMgrInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.Person BrokerInfo {
            get {
                return this.BrokerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerInfoField, value) != true)) {
                    this.BrokerInfoField = value;
                    this.RaisePropertyChanged("BrokerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.InitialServices InitialServices {
            get {
                return this.InitialServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialServicesField, value) != true)) {
                    this.InitialServicesField = value;
                    this.RaisePropertyChanged("InitialServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitle {
            get {
                return this.PageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitleField, value) != true)) {
                    this.PageTitleField = value;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.PropertyHistoryItem[] PropertyHistory {
            get {
                return this.PropertyHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyHistoryField, value) != true)) {
                    this.PropertyHistoryField = value;
                    this.RaisePropertyChanged("PropertyHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientDashboard.reoSvc.UtilityStatus[] UtilStatus {
            get {
                return this.UtilStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilStatusField, value) != true)) {
                    this.UtilStatusField = value;
                    this.RaisePropertyChanged("UtilStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessInfo", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class AccessInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockboxCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyCode {
            get {
                return this.KeyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyCodeField, value) != true)) {
                    this.KeyCodeField = value;
                    this.RaisePropertyChanged("KeyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockboxCode {
            get {
                return this.LockboxCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LockboxCodeField, value) != true)) {
                    this.LockboxCodeField = value;
                    this.RaisePropertyChanged("LockboxCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class AdditionalPropertyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DaysInInventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ElevationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOAInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LawnSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LotSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlumbingSystemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysInInventory {
            get {
                return this.DaysInInventoryField;
            }
            set {
                if ((this.DaysInInventoryField.Equals(value) != true)) {
                    this.DaysInInventoryField = value;
                    this.RaisePropertyChanged("DaysInInventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Elevation {
            get {
                return this.ElevationField;
            }
            set {
                if ((this.ElevationField.Equals(value) != true)) {
                    this.ElevationField = value;
                    this.RaisePropertyChanged("Elevation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOAInfo {
            get {
                return this.HOAInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.HOAInfoField, value) != true)) {
                    this.HOAInfoField = value;
                    this.RaisePropertyChanged("HOAInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LawnSize {
            get {
                return this.LawnSizeField;
            }
            set {
                if ((this.LawnSizeField.Equals(value) != true)) {
                    this.LawnSizeField = value;
                    this.RaisePropertyChanged("LawnSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LotSize {
            get {
                return this.LotSizeField;
            }
            set {
                if ((this.LotSizeField.Equals(value) != true)) {
                    this.LotSizeField = value;
                    this.RaisePropertyChanged("LotSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlumbingSystem {
            get {
                return this.PlumbingSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.PlumbingSystemField, value) != true)) {
                    this.PlumbingSystemField = value;
                    this.RaisePropertyChanged("PlumbingSystem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetInfo", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class AssetInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InVPRAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MultipleUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InVPRArea {
            get {
                return this.InVPRAreaField;
            }
            set {
                if ((this.InVPRAreaField.Equals(value) != true)) {
                    this.InVPRAreaField = value;
                    this.RaisePropertyChanged("InVPRArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanNumber {
            get {
                return this.LoanNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanNumberField, value) != true)) {
                    this.LoanNumberField = value;
                    this.RaisePropertyChanged("LoanNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MultipleUnits {
            get {
                return this.MultipleUnitsField;
            }
            set {
                if ((this.MultipleUnitsField.Equals(value) != true)) {
                    this.MultipleUnitsField = value;
                    this.RaisePropertyChanged("MultipleUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyStatus {
            get {
                return this.PropertyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyStatusField, value) != true)) {
                    this.PropertyStatusField = value;
                    this.RaisePropertyChanged("PropertyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyType {
            get {
                return this.PropertyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTypeField, value) != true)) {
                    this.PropertyTypeField = value;
                    this.RaisePropertyChanged("PropertyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitQuantity {
            get {
                return this.UnitQuantityField;
            }
            set {
                if ((this.UnitQuantityField.Equals(value) != true)) {
                    this.UnitQuantityField = value;
                    this.RaisePropertyChanged("UnitQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitialServices", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class InitialServices : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InitialGrassCutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RekeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SalesCleanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TrashoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> WinterizationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InitialGrassCut {
            get {
                return this.InitialGrassCutField;
            }
            set {
                if ((this.InitialGrassCutField.Equals(value) != true)) {
                    this.InitialGrassCutField = value;
                    this.RaisePropertyChanged("InitialGrassCut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Rekey {
            get {
                return this.RekeyField;
            }
            set {
                if ((this.RekeyField.Equals(value) != true)) {
                    this.RekeyField = value;
                    this.RaisePropertyChanged("Rekey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SalesClean {
            get {
                return this.SalesCleanField;
            }
            set {
                if ((this.SalesCleanField.Equals(value) != true)) {
                    this.SalesCleanField = value;
                    this.RaisePropertyChanged("SalesClean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Trashout {
            get {
                return this.TrashoutField;
            }
            set {
                if ((this.TrashoutField.Equals(value) != true)) {
                    this.TrashoutField = value;
                    this.RaisePropertyChanged("Trashout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Winterization {
            get {
                return this.WinterizationField;
            }
            set {
                if ((this.WinterizationField.Equals(value) != true)) {
                    this.WinterizationField = value;
                    this.RaisePropertyChanged("Winterization");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyHistoryItem", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class PropertyHistoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientInvoiceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletionUploadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> JobCompletionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkOrderTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BidDate {
            get {
                return this.BidDateField;
            }
            set {
                if ((this.BidDateField.Equals(value) != true)) {
                    this.BidDateField = value;
                    this.RaisePropertyChanged("BidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidNumber {
            get {
                return this.BidNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BidNumberField, value) != true)) {
                    this.BidNumberField = value;
                    this.RaisePropertyChanged("BidNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((this.BillDateField.Equals(value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientInvoiceAmount {
            get {
                return this.ClientInvoiceAmountField;
            }
            set {
                if ((this.ClientInvoiceAmountField.Equals(value) != true)) {
                    this.ClientInvoiceAmountField = value;
                    this.RaisePropertyChanged("ClientInvoiceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletionUploadDate {
            get {
                return this.CompletionUploadDateField;
            }
            set {
                if ((this.CompletionUploadDateField.Equals(value) != true)) {
                    this.CompletionUploadDateField = value;
                    this.RaisePropertyChanged("CompletionUploadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> JobCompletionDate {
            get {
                return this.JobCompletionDateField;
            }
            set {
                if ((this.JobCompletionDateField.Equals(value) != true)) {
                    this.JobCompletionDateField = value;
                    this.RaisePropertyChanged("JobCompletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanNumber {
            get {
                return this.LoanNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanNumberField, value) != true)) {
                    this.LoanNumberField = value;
                    this.RaisePropertyChanged("LoanNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPhotos {
            get {
                return this.NumberOfPhotosField;
            }
            set {
                if ((this.NumberOfPhotosField.Equals(value) != true)) {
                    this.NumberOfPhotosField = value;
                    this.RaisePropertyChanged("NumberOfPhotos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOrderNumber {
            get {
                return this.WorkOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderNumberField, value) != true)) {
                    this.WorkOrderNumberField = value;
                    this.RaisePropertyChanged("WorkOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOrderType {
            get {
                return this.WorkOrderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderTypeField, value) != true)) {
                    this.WorkOrderTypeField = value;
                    this.RaisePropertyChanged("WorkOrderType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilityStatus", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.Core.ViewModels.Common")]
    [System.SerializableAttribute()]
    public partial class UtilityStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UtilStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UtilStatus {
            get {
                return this.UtilStatusField;
            }
            set {
                if ((this.UtilStatusField.Equals(value) != true)) {
                    this.UtilStatusField = value;
                    this.RaisePropertyChanged("UtilStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilType {
            get {
                return this.UtilTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilTypeField, value) != true)) {
                    this.UtilTypeField = value;
                    this.RaisePropertyChanged("UtilType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="reoSvc.IREOService")]
    public interface IREOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREOService/GetReoPropertyInfo", ReplyAction="http://tempuri.org/IREOService/GetReoPropertyInfoResponse")]
        ClientDashboard.reoSvc.REOPropertyInfo GetReoPropertyInfo(int organizationID, string loanNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREOService/GetReoPropertyInfo", ReplyAction="http://tempuri.org/IREOService/GetReoPropertyInfoResponse")]
        System.Threading.Tasks.Task<ClientDashboard.reoSvc.REOPropertyInfo> GetReoPropertyInfoAsync(int organizationID, string loanNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IREOServiceChannel : ClientDashboard.reoSvc.IREOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class REOServiceClient : System.ServiceModel.ClientBase<ClientDashboard.reoSvc.IREOService>, ClientDashboard.reoSvc.IREOService {
        
        public REOServiceClient() {
        }
        
        public REOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public REOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public REOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public REOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientDashboard.reoSvc.REOPropertyInfo GetReoPropertyInfo(int organizationID, string loanNumber) {
            return base.Channel.GetReoPropertyInfo(organizationID, loanNumber);
        }
        
        public System.Threading.Tasks.Task<ClientDashboard.reoSvc.REOPropertyInfo> GetReoPropertyInfoAsync(int organizationID, string loanNumber) {
            return base.Channel.GetReoPropertyInfoAsync(organizationID, loanNumber);
        }
    }
}
